### ISSUE TITLE
Run the Zend testsuite to ensure consistency between implementation

### ISSUE THREAD

**Issue by stof** [tagua-vm/tagua-vm#22]
It would be great to run the Zend testsuite to detect inconsistencies. HHVM does that for instance.

I don't know whether this project is ready to start such step yet of if it is too early in the development, but this should be considered an important step when starting to provide language features IMO.
The testsuite should be taken from the php-src version corresponding to the version advocated by the `PHP_VERSION_ID` when running code in the VM.

**Comment by Hywan** [comment]
Hello :-),

This is something we are definitively going to do. The project is not ready yet but having a conformance test suite is the basis for us.

Thanks!
