### ISSUE TITLE
Publish the PHP parser as an independent library

### ISSUE THREAD

**Issue by msjyoo** [tagua-vm/tagua-vm#27]
Hello,

I'd love to use a Rust PHP parser for a project, but I'm not good enough to build my own. Any chance the parser can be published into its own independent library without the compiler / VM?

**Comment by Hywan** [comment]
Hello,

Probably yes. This is something I am planning but I can't provide any deadline. What's yours?

**Comment by msjyoo** [comment]
No deadline, it's just a hobby project to learn Rust :)

**Comment by Hywan** [comment]
Is it OK if I close the issue?

**Comment by Hywan** [comment]
Fixed by #42.

**Comment by Hywan** [comment]
The new parser repository is here, https://github.com/tagua-vm/parser. Documentation is coming :smiley:.

**Comment by msjyoo** [comment]
Yaaay! Thanks vm (very much) :D

**Comment by Hywan** [comment]
Haha ;-), good catch!
