### ISSUE TITLE
IRC Channel on Freenode?

### ISSUE THREAD

**Issue by msjyoo** [tagua-vm/tagua-vm#46]
Hello,

It would be great to have a chat forum, for example a channel on Freenode?

Thanks.

**Comment by Hywan** [comment]
Hello :-),

Yup, you're right. So far, we are using `#hoaproject-tagua` on Freenode but this is not official.

Maybe @jubianchi could add a Gitter channel, with a bot to sync with a new `#taguavm` channel on Freenode? Do you have time for that?

**Comment by jubianchi** [comment]
The IRC channel is ready: [irc://irc.freenode.net/taguavm](irc://irc.freenode.net/taguavm)

**Comment by Hywan** [comment]
Github notification for all Tagua VM repositories are set up.
Request to BotBot.me has been submit.

**Comment by jubianchi** [comment]
Gitter room is online: https://gitter.im/tagua-vm/tagua-vm

**Comment by jubianchi** [comment]
And please welcome @taguavm-bot
